### ISSUE TITLE
Clonar o projeto no seu eclipse

### ISSUE THREAD

**Issue by brunoqp78** [rogeriolimap1/Projeto_Maven_JPA#1]
Rogério, clone o repositório no eclipse

**Comment by brunoqp78** [comment]
Link da aula (extra) onde explico isso: https://drive.google.com/file/d/1l-VT5ikP_rgzAbaR4uAsTdTwktXbLjae/view

**Comment by rogeriolimap1** [comment]
Clonado

**Comment by rogeriolimap1** [comment]
[A9 - (Etapa 5).zip](https://github.com/rogeriolimap1/Projeto_Maven_JPA/files/7628000/A9.-.Etapa.5.zip)
